const FM = {
  myTeam:     "맨체스터 시티",
  myLeague:   "epl",
  season:     "2074/75",
  leagueName: "잉글랜드 프리미어 리그",
  leagueFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  teamColor:  "#6CABDD",

  // 2074/75 시즌 최종 순위
  standings: [
    { pos:1,  team:"맨체스터 시티",  played:38, won:27, drawn:7,  lost:4,  gf:106, ga:25,  pts:88,  form:["W","W","W","W","W"] },
    { pos:2,  team:"올브스",         played:38, won:27, drawn:7,  lost:4,  gf:88,  ga:30,  pts:88,  form:["W","W","D","W","W"] },
    { pos:3,  team:"리버풀",         played:38, won:23, drawn:9,  lost:6,  gf:86,  ga:37,  pts:78,  form:["W","D","W","L","W"] },
    { pos:4,  team:"카디프 시티",    played:38, won:22, drawn:4,  lost:12, gf:72,  ga:56,  pts:70,  form:["W","W","L","W","D"] },
    { pos:5,  team:"팰리스",         played:38, won:21, drawn:7,  lost:10, gf:76,  ga:62,  pts:70,  form:["W","L","W","D","W"] },
    { pos:6,  team:"아스톤 빌라",    played:38, won:20, drawn:6,  lost:12, gf:64,  ga:47,  pts:66,  form:["L","W","W","D","W"] },
    { pos:7,  team:"입스위치 타운",  played:38, won:18, drawn:8,  lost:12, gf:54,  ga:39,  pts:62,  form:["W","D","L","W","W"] },
    { pos:8,  team:"풀햄",           played:38, won:16, drawn:10, lost:12, gf:65,  ga:57,  pts:58,  form:["D","W","L","W","D"] },
    { pos:9,  team:"뉴캐슬",         played:38, won:17, drawn:6,  lost:15, gf:63,  ga:54,  pts:57,  form:["L","W","W","L","W"] },
    { pos:10, team:"본머스",         played:38, won:15, drawn:5,  lost:18, gf:50,  ga:69,  pts:50,  form:["L","D","W","L","W"] },
    { pos:11, team:"브라이튼 FC",    played:38, won:13, drawn:9,  lost:16, gf:55,  ga:78,  pts:48,  form:["D","L","W","D","L"] },
    { pos:12, team:"토트넘",         played:38, won:13, drawn:8,  lost:17, gf:64,  ga:65,  pts:47,  form:["L","W","D","L","W"] },
    { pos:13, team:"맨 레드",        played:38, won:14, drawn:5,  lost:19, gf:56,  ga:67,  pts:47,  form:["W","L","L","W","D"] },
    { pos:14, team:"첼시",           played:38, won:11, drawn:10, lost:17, gf:51,  ga:66,  pts:43,  form:["D","L","W","D","L"] },
    { pos:15, team:"브렌트포드",     played:38, won:12, drawn:7,  lost:19, gf:42,  ga:61,  pts:43,  form:["L","W","L","L","D"] },
    { pos:16, team:"아스날",         played:38, won:11, drawn:9,  lost:18, gf:44,  ga:61,  pts:42,  form:["D","W","L","D","L"] },
    { pos:17, team:"브리스틀 시티",  played:38, won:9,  drawn:8,  lost:21, gf:34,  ga:62,  pts:35,  form:["L","L","D","W","L"] },
    { pos:18, team:"리즈",           played:38, won:8,  drawn:10, lost:20, gf:47,  ga:70,  pts:34,  form:["D","L","L","D","W"] },
    { pos:19, team:"보스턴 Utd",     played:38, won:7,  drawn:8,  lost:23, gf:28,  ga:64,  pts:29,  form:["L","L","W","L","L"] },
    { pos:20, team:"렉섬 AFC",       played:38, won:3,  drawn:3,  lost:32, gf:36,  ga:111, pts:12,  form:["L","L","L","L","L"] },
  ],

  matches: [
    {
      id:"r35_mc_sc", round:35, date:"2075-03-08", status:"NS",
      home:"맨체스터 시티", homeScore:null,
      away:"SC 프라이부르크", awayScore:null,
      stadium:"Etihad Stadium",
    },
  ],

  // loan:true = 임대 나간 선수
  // career: 클럽 커리어 배열 { club, from, to, loan(optional) }
  // cityRecord: 맨시티 시즌별 기록 배열 { season, apps, goals, assists, rating }
  // seasonStats: 75/76 시즌 진행 중 기록 (초기화 상태)
  players: [
    // ── GK ──────────────────────────────────
    { id:"p_cho",       name:"조성현",              nameEn:"Jo Seong-hyeon",     pos:"GK",                    no:30, age:32, nationality:"한국",        loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_matheus",   name:"마를롱 마테우스",     nameEn:"Marlon Matheus",     pos:"GK",                    no:25, age:30, nationality:"브라질",      loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_bowman",    name:"대니 보먼",            nameEn:"Danny Bowman",       pos:"GK",                    no:61, age:19, nationality:"잉글랜드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_cima",      name:"살바토레 치마",        nameEn:"Salvatore Cima",     pos:"GK",                    no:32, age:20, nationality:"잉글랜드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    // ── DF ──────────────────────────────────
    {
      id:"p_alves", name:"이보 알베스", nameEn:"Ivo Alves",
      pos:"D (L)", no:2, age:27, nationality:"포르투갈", loan:false,
      seasonStats:{ apps:0, goals:0, assists:0, rating:null },
      career:[
        { club:"SL 벤피카",       from:"2062", to:"2071" },
        { club:"코번트리 시티",   from:"2065", to:"2066", loan:true },
        { club:"인터 밀란",       from:"2071", to:"2072" },
        { club:"맨체스터 시티",   from:"2072", to:null   },
      ],
      cityRecord:[
        { season:"2072/73", apps:53, goals:1, assists:3, rating:6.93 },
        { season:"2073/74", apps:36, goals:2, assists:4, rating:7.09 },
        { season:"2074/75", apps:37, goals:0, assists:4, rating:7.03 },
      ],
    },
    { id:"p_koopman",   name:"론 코프만",            nameEn:"Ron Koopman",        pos:"D (L)",                 no:3,  age:30, nationality:"네덜란드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_stoyanov",  name:"알렉산다르 스토야노프",nameEn:"Alexandar Stoyanov", pos:"D (C)",                 no:4,  age:30, nationality:"불가리아",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_fabio",     name:"파비우 조세",           nameEn:"Fábio José",         pos:"D (C)",                 no:5,  age:26, nationality:"브라질",      loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_mbaye",     name:"포르모스 음바예",       nameEn:"Formose Mbaye",      pos:"D (C), DM, M (C)",      no:6,  age:27, nationality:"세네갈",      loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_milojevic", name:"라도미르 밀로예비치",   nameEn:"Radomir Milojević",  pos:"D (RC)",                no:18, age:31, nationality:"세르비아",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_dixon",     name:"마이크 딕슨",           nameEn:"Mike Dixon",         pos:"D (RL)",                no:26, age:25, nationality:"아일랜드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_miles",     name:"조지 마일스",           nameEn:"George Miles",       pos:"D (RLC)",               no:41, age:22, nationality:"잉글랜드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_parsley",   name:"시릴 파슬리",           nameEn:"Cyril Parsley",      pos:"D (C)",                 no:50, age:23, nationality:"잉글랜드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_bentley",   name:"레스 벤틀리",           nameEn:"Les Bentley",        pos:"D (RC), DM",            no:55, age:17, nationality:"잉글랜드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_evans",     name:"조나단 에반스",         nameEn:"Jonathan Evans",     pos:"D (LC)",                no:38, age:16, nationality:"잉글랜드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_maynard",   name:"리키 메이나드",         nameEn:"Ricky Maynard",      pos:"D (C), DM, M (LC)",     no:null, age:21, nationality:"잉글랜드",  loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_cudworth",  name:"마이클 커드워스",       nameEn:"Michael Cudworth",   pos:"D (C), DM",             no:null, age:21, nationality:"북아일랜드", loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_joejohn",   name:"조 존",                 nameEn:"Joe John",           pos:"D (C)",                 no:null, age:21, nationality:"웨일스",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    // ── MF ──────────────────────────────────
    { id:"p_butler",    name:"크리스 버틀러",         nameEn:"Kris Butler",        pos:"DM, M (LC)",            no:8,  age:26, nationality:"웨일스",      loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_yucel",     name:"얀 위첼",               nameEn:"Can Yücel",          pos:"M (L), AM (RL)",        no:11, age:34, nationality:"독일",        loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_vitor",     name:"빅토르",                nameEn:"Vítor",              pos:"M/AM (L)",              no:13, age:32, nationality:"브라질",      loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_henry",     name:"렌 헨리",               nameEn:"Len Henry",          pos:"D (RC), DM",            no:15, age:24, nationality:"잉글랜드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_senior",    name:"타이리스 시니어",       nameEn:"Tyreece Senior",     pos:"D (C), DM, M (C)",      no:16, age:22, nationality:"잉글랜드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_vega",      name:"라우타로 베가",         nameEn:"Lautaro Vega",       pos:"WB (R), AM (C)",        no:17, age:24, nationality:"아르헨티나",  loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_becker",    name:"아담 베커",             nameEn:"Adam Becker",        pos:"M/AM (R)",              no:20, age:28, nationality:"폴란드",      loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_perarnau",  name:"안토니 페라르나우",     nameEn:"Antoni Perarnau",    pos:"DM, M/AM (C)",          no:22, age:23, nationality:"스페인",      loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_steinacher",name:"마티아스 슈타이나허",   nameEn:"Mathias Steinacher", pos:"M/AM (C)",              no:24, age:22, nationality:"독일",        loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_pappas",    name:"야니스 파파스",         nameEn:"Giannis Pappas",     pos:"M/AM (C)",              no:7,  age:27, nationality:"독일",        loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_gryzlak",   name:"파웰 그리즐락",         nameEn:"Pawel Gryżlak",      pos:"D (C), DM, M/AM (C)",   no:37, age:24, nationality:"폴란드",      loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_moreira",   name:"베르나르도 모레이라",   nameEn:"Bernardo Moreira",   pos:"M (R), AM (RC)",        no:45, age:29, nationality:"네덜란드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_wijdenbosch",name:"키야나 바이던보스",    nameEn:"Ki-Jana Wijdenbosch",pos:"DM, M/AM (C), ST (C)",  no:90, age:28, nationality:"네덜란드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_shimizu",   name:"토루 시미즈",           nameEn:"Toru Shimizu",       pos:"M/AM (L)",              no:35, age:25, nationality:"독일",        loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_mcconaghy", name:"로비 맥코나이",         nameEn:"Robbie McConaghy",   pos:"AM (RLC)",              no:36, age:17, nationality:"스코틀랜드",  loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_estrada",   name:"제르만 에스트라다",     nameEn:"Germán Estrada",     pos:"AM (R)",                no:29, age:23, nationality:"멕시코",      loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_kvello",    name:"에밀 오베센 크벨로",   nameEn:"Emil Ovesen Kvello", pos:"AM (RC), ST (C)",       no:92, age:18, nationality:"노르웨이",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_morrison",  name:"블레어 모리슨",         nameEn:"Blair Morrison",     pos:"DM, M/AM (C)",          no:null, age:20, nationality:"스코틀랜드", loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_sunomata",  name:"토루 스노마타",         nameEn:"Toru Sunomata",      pos:"M/AM (L)",              no:93, age:19, nationality:"일본",        loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_mcwilliam", name:"바니 맥윌리엄",         nameEn:"Barney McWilliam",   pos:"DM, M (C)",             no:33, age:16, nationality:"잉글랜드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    // ── FW ──────────────────────────────────
    { id:"p_thompson",  name:"조지 톰프슨",           nameEn:"George Thompson",    pos:"AM (RLC), ST (C)",      no:9,  age:25, nationality:"잉글랜드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_tejero",    name:"프란시스코 테헤로",     nameEn:"Francisco Tejero",   pos:"M/AM (C)",              no:77, age:20, nationality:"스페인",      loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_marfil",    name:"엔리케 마르필",         nameEn:"Enrique Marfil",     pos:"M (L), AM (RL), ST (C)",no:39, age:19, nationality:"스페인",      loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_hughes",    name:"코디 휴즈",             nameEn:"Cody Hughes",        pos:"AM (RL), ST (C)",       no:40, age:22, nationality:"잉글랜드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_baird",     name:"콜린 베어드",           nameEn:"Colin Baird",        pos:"M/AM (C), ST (C)",      no:42, age:17, nationality:"잉글랜드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_bove",      name:"알렉스 보브",           nameEn:"Alex Bove",          pos:"AM (R), ST (C)",        no:95, age:null, nationality:"아일랜드",  loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_lynchey",   name:"애슬리 린치",           nameEn:"Astley Lynchey",     pos:"M/AM (R), ST (C)",      no:31, age:17, nationality:"잉글랜드",    loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_gurrutxaga",name:"고르카 구루차하",       nameEn:"Gorka Gurrutxaga",   pos:"AM (RLC), ST (C)",      no:34, age:20, nationality:"스페인",      loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_santi",     name:"산티",                  nameEn:"Santi",              pos:"M/AM (C)",              no:null, age:21, nationality:"잉글랜드",  loan:false, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    // ── 임대 ────────────────────────────────
    { id:"p_webb",      name:"딜런 웹",               nameEn:"Dylan Webb",         pos:"M/AM (L)",              no:null, age:28, nationality:"잉글랜드",  loan:true, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_havern",    name:"가리 하번",             nameEn:"Gari Havern",        pos:"M/AM (C), ST (C)",      no:null, age:25, nationality:"잉글랜드",  loan:true, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_rafael",    name:"하파엘",                nameEn:"Rafael",             pos:"ST (C)",                no:null, age:25, nationality:"브라질",    loan:true, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
    { id:"p_calder",    name:"샘 콜더",               nameEn:"Sam Calder",         pos:"M/AM (C)",              no:null, age:22, nationality:"잉글랜드",  loan:true, seasonStats:{ apps:0, goals:0, assists:0, rating:null } },
  ],
};
