const FM = {
  myTeam:     "맨체스터 시티",
  myLeague:   "epl",
  season:     "75/3/3",
  leagueName: "잉글랜드 프리미어 리그",
  leagueFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  teamColor:  "#6CABDD",

  standings: [
    { pos:1,  team:"맨체스터 시티",        played:34, won:24, drawn:5,  lost:5,  gf:78, ga:34, pts:77, form:["W","W","D","W","W"], prev:1 },
    { pos:2,  team:"아스널",               played:34, won:23, drawn:6,  lost:5,  gf:71, ga:31, pts:75, form:["W","W","W","L","W"], prev:3 },
    { pos:3,  team:"리버풀",               played:34, won:22, drawn:7,  lost:5,  gf:74, ga:38, pts:73, form:["D","W","W","W","D"], prev:2 },
    { pos:4,  team:"첼시",                 played:34, won:19, drawn:8,  lost:7,  gf:63, ga:44, pts:65, form:["W","L","W","W","D"], prev:5 },
    { pos:5,  team:"토트넘",               played:34, won:18, drawn:6,  lost:10, gf:60, ga:50, pts:60, form:["L","W","W","D","L"], prev:4 },
    { pos:6,  team:"뉴캐슬",               played:34, won:17, drawn:5,  lost:12, gf:58, ga:48, pts:56, form:["W","D","L","W","W"], prev:6 },
    { pos:7,  team:"애스턴 빌라",          played:34, won:16, drawn:6,  lost:12, gf:54, ga:51, pts:54, form:["D","W","L","D","W"], prev:8 },
    { pos:8,  team:"맨체스터 유나이티드",  played:34, won:14, drawn:7,  lost:13, gf:49, ga:52, pts:49, form:["L","L","W","D","W"], prev:7 },
    { pos:9,  team:"웨스트햄",             played:34, won:12, drawn:9,  lost:13, gf:47, ga:55, pts:45, form:["D","W","L","L","D"], prev:9 },
    { pos:10, team:"브라이튼",             played:34, won:12, drawn:8,  lost:14, gf:52, ga:57, pts:44, form:["W","D","W","L","L"], prev:11 },
    { pos:11, team:"풀럼",                 played:34, won:11, drawn:9,  lost:14, gf:43, ga:53, pts:42, form:["L","D","D","W","L"], prev:10 },
    { pos:12, team:"브렌트포드",           played:34, won:10, drawn:10, lost:14, gf:45, ga:55, pts:40, form:["D","L","D","W","D"], prev:12 },
    { pos:13, team:"크리스탈 팰리스",      played:34, won:10, drawn:7,  lost:17, gf:38, ga:56, pts:37, form:["L","W","L","D","L"], prev:13 },
    { pos:14, team:"울버햄튼",             played:34, won:9,  drawn:9,  lost:16, gf:36, ga:54, pts:36, form:["D","D","L","W","D"], prev:14 },
    { pos:15, team:"에버턴",               played:34, won:8,  drawn:10, lost:16, gf:33, ga:55, pts:34, form:["L","D","W","D","L"], prev:16 },
    { pos:16, team:"노팅엄 포레스트",      played:34, won:8,  drawn:9,  lost:17, gf:32, ga:58, pts:33, form:["W","L","D","L","W"], prev:15 },
    { pos:17, team:"본머스",               played:34, won:7,  drawn:10, lost:17, gf:35, ga:61, pts:31, form:["D","L","L","D","L"], prev:17 },
    { pos:18, team:"루턴 타운",            played:34, won:6,  drawn:8,  lost:20, gf:28, ga:66, pts:26, form:["L","L","D","L","L"], prev:18 },
    { pos:19, team:"번리",                 played:34, won:5,  drawn:6,  lost:23, gf:25, ga:73, pts:21, form:["L","L","L","D","L"], prev:19 },
    { pos:20, team:"셰필드 유나이티드",    played:34, won:4,  drawn:5,  lost:25, gf:22, ga:82, pts:17, form:["L","D","L","L","L"], prev:20 },
  ],

  matches: [
    {
      id:"r35_mc_sc", round:35, date:"2075-03-08", status:"NS",
      home:"맨체스터 시티", homeScore:null,
      away:"SC 프라이부르크", awayScore:null,
      stadium:"Etihad Stadium",
    },
  ],

  // loan:true = 임대 나간 선수
  players: [
    // ── GK ──────────────────────────────────
    { id:"p_cho",      name:"조성현",           nameEn:"Jo Seong-hyeon",    pos:"GK",                    no:30, age:32, nationality:"한국",       loan:false, seasonStats:{ apps:11,   goals:0,  assists:0, rating:7.22 } },
    { id:"p_matheus",  name:"마를롱 마테우스",  nameEn:"Marlon Matheus",     pos:"GK",                    no:25, age:30, nationality:"브라질",     loan:false, seasonStats:{ apps:35,   goals:0,  assists:0, rating:7.15 } },
    { id:"p_bowman",   name:"대니 보먼",         nameEn:"Danny Bowman",       pos:"GK",                    no:61, age:19, nationality:"잉글랜드",   loan:false, seasonStats:{ apps:null, goals:null, assists:null, rating:null } },
    { id:"p_cima",     name:"살바토레 치마",     nameEn:"Salvatore Cima",     pos:"GK",                    no:32, age:20, nationality:"잉글랜드",   loan:false, seasonStats:{ apps:null, goals:null, assists:null, rating:7.24 } },
    // ── DF ──────────────────────────────────
    { id:"p_alves",    name:"이보 알베스",       nameEn:"Ivo Alves",          pos:"D (L)",                 no:2,  age:27, nationality:"포르투갈",   loan:false, seasonStats:{ apps:22,   goals:0,  assists:2, rating:7.04 } },
    { id:"p_koopman",  name:"론 코프만",         nameEn:"Ron Koopman",        pos:"D (L)",                 no:3,  age:30, nationality:"네덜란드",   loan:false, seasonStats:{ apps:24,   goals:1,  assists:0, rating:7.18 } },
    { id:"p_stoyanov", name:"알렉산다르 스토야노프", nameEn:"Alexandar Stoyanov", pos:"D (C)",             no:4,  age:30, nationality:"불가리아",   loan:false, seasonStats:{ apps:24,   goals:0,  assists:0, rating:7.11 } },
    { id:"p_fabio",    name:"파비우 조세",       nameEn:"Fábio José",         pos:"D (C)",                 no:5,  age:26, nationality:"브라질",     loan:false, seasonStats:{ apps:28,   goals:0,  assists:0, rating:7.06 } },
    { id:"p_mbaye",    name:"포르모스 음바예",   nameEn:"Formose Mbaye",      pos:"D (C), DM, M (C)",      no:6,  age:27, nationality:"세네갈",     loan:false, seasonStats:{ apps:3,    goals:1,  assists:2, rating:8.00 } },
    { id:"p_milojevic",name:"라도미르 밀로예비치",nameEn:"Radomir Milojević",  pos:"D (RC)",                no:18, age:31, nationality:"세르비아",   loan:false, seasonStats:{ apps:18,   goals:1,  assists:1, rating:7.02 } },
    { id:"p_dixon",    name:"마이크 딕슨",       nameEn:"Mike Dixon",         pos:"D (RL)",                no:26, age:25, nationality:"아일랜드",   loan:false, seasonStats:{ apps:28,   goals:0,  assists:3, rating:6.79 } },
    { id:"p_miles",    name:"조지 마일스",       nameEn:"George Miles",       pos:"D (RLC)",               no:41, age:22, nationality:"잉글랜드",   loan:false, seasonStats:{ apps:null, goals:null, assists:null, rating:7.08 } },
    { id:"p_parsley",  name:"시릴 파슬리",       nameEn:"Cyril Parsley",      pos:"D (C)",                 no:50, age:23, nationality:"잉글랜드",   loan:false, seasonStats:{ apps:5,    goals:0,  assists:0, rating:7.08 } },
    { id:"p_bentley",  name:"레스 벤틀리",       nameEn:"Les Bentley",        pos:"D (RC), DM",            no:55, age:17, nationality:"잉글랜드",   loan:false, seasonStats:{ apps:9,    goals:0,  assists:0, rating:6.95 } },
    { id:"p_evans",    name:"조나단 에반스",     nameEn:"Jonathan Evans",     pos:"D (LC)",                no:38, age:16, nationality:"잉글랜드",   loan:false, seasonStats:{ apps:null, goals:null, assists:null, rating:7.10 } },
    { id:"p_maynard",  name:"리키 메이나드",     nameEn:"Ricky Maynard",      pos:"D (C), DM, M (LC)",     no:null, age:21, nationality:"잉글랜드", loan:false, seasonStats:{ apps:33,   goals:4,  assists:2, rating:6.81 } },
    { id:"p_cudworth", name:"마이클 커드워스",   nameEn:"Michael Cudworth",   pos:"D (C), DM",             no:null, age:21, nationality:"북아일랜드",loan:false, seasonStats:{ apps:null, goals:null, assists:null, rating:6.88 } },
    { id:"p_joejohn",  name:"조 존",             nameEn:"Joe John",           pos:"D (C)",                 no:null, age:21, nationality:"웨일스",   loan:false, seasonStats:{ apps:null, goals:null, assists:null, rating:7.12 } },
    // ── MF ──────────────────────────────────
    { id:"p_butler",   name:"크리스 버틀러",     nameEn:"Kris Butler",        pos:"DM, M (LC)",            no:8,  age:26, nationality:"웨일스",     loan:false, seasonStats:{ apps:25,   goals:4,  assists:8,  rating:7.32 } },
    { id:"p_yucel",    name:"얀 위첼",           nameEn:"Can Yücel",          pos:"M (L), AM (RL)",        no:11, age:34, nationality:"독일",       loan:false, seasonStats:{ apps:21,   goals:6,  assists:11, rating:7.20 } },
    { id:"p_vitor",    name:"빅토르",            nameEn:"Vítor",              pos:"M/AM (L)",              no:13, age:32, nationality:"브라질",     loan:false, seasonStats:{ apps:19,   goals:5,  assists:5,  rating:7.00 } },
    { id:"p_henry",    name:"렌 헨리",           nameEn:"Len Henry",          pos:"D (RC), DM",            no:15, age:24, nationality:"잉글랜드",   loan:false, seasonStats:{ apps:5,    goals:0,  assists:0,  rating:6.93 } },
    { id:"p_senior",   name:"타이리스 시니어",   nameEn:"Tyreece Senior",     pos:"D (C), DM, M (C)",      no:16, age:22, nationality:"잉글랜드",   loan:false, seasonStats:{ apps:13,   goals:0,  assists:1,  rating:6.99 } },
    { id:"p_vega",     name:"라우타로 베가",     nameEn:"Lautaro Vega",       pos:"WB (R), AM (C)",        no:17, age:24, nationality:"아르헨티나", loan:false, seasonStats:{ apps:24,   goals:4,  assists:8,  rating:7.04 } },
    { id:"p_becker",   name:"아담 베커",         nameEn:"Adam Becker",        pos:"M/AM (R)",              no:20, age:28, nationality:"폴란드",     loan:false, seasonStats:{ apps:10,   goals:5,  assists:9,  rating:7.29 } },
    { id:"p_perarnau", name:"안토니 페라르나우", nameEn:"Antoni Perarnau",    pos:"DM, M/AM (C)",          no:22, age:23, nationality:"스페인",     loan:false, seasonStats:{ apps:0,    goals:0,  assists:0,  rating:7.00 } },
    { id:"p_steinacher",name:"마티아스 슈타이나허",nameEn:"Mathias Steinacher",pos:"M/AM (C)",             no:24, age:22, nationality:"독일",       loan:false, seasonStats:{ apps:14,   goals:7,  assists:4,  rating:7.11 } },
    { id:"p_pappas",   name:"야니스 파파스",     nameEn:"Giannis Pappas",     pos:"M/AM (C)",              no:7,  age:27, nationality:"독일",       loan:false, seasonStats:{ apps:28,   goals:12, assists:10, rating:7.27 } },
    { id:"p_gryzlak",  name:"파웰 그리즐락",     nameEn:"Pawel Gryżlak",      pos:"D (C), DM, M/AM (C)",   no:37, age:24, nationality:"폴란드",     loan:false, seasonStats:{ apps:15,   goals:7,  assists:4,  rating:7.14 } },
    { id:"p_moreira",  name:"베르나르도 모레이라",nameEn:"Bernardo Moreira",   pos:"M (R), AM (RC)",        no:45, age:29, nationality:"네덜란드",   loan:false, seasonStats:{ apps:4,    goals:4,  assists:3,  rating:7.16 } },
    { id:"p_wijdenbosch",name:"키야나 바이던보스",nameEn:"Ki-Jana Wijdenbosch",pos:"DM, M/AM (C), ST (C)",  no:90, age:28, nationality:"네덜란드",   loan:false, seasonStats:{ apps:21,   goals:21, assists:4,  rating:7.25 } },
    { id:"p_shimizu",  name:"토루 시미즈",       nameEn:"Toru Shimizu",       pos:"M/AM (L)",              no:35, age:25, nationality:"독일",       loan:false, seasonStats:{ apps:17,   goals:5,  assists:5,  rating:7.12 } },
    { id:"p_mcconaghy",name:"로비 맥코나이",     nameEn:"Robbie McConaghy",   pos:"AM (RLC)",              no:36, age:17, nationality:"스코틀랜드", loan:false, seasonStats:{ apps:null, goals:null, assists:null, rating:7.64 } },
    { id:"p_estrada",  name:"제르만 에스트라다", nameEn:"Germán Estrada",      pos:"AM (R)",                no:29, age:23, nationality:"멕시코",     loan:false, seasonStats:{ apps:17,   goals:6,  assists:9,  rating:7.24 } },
    { id:"p_kvello",   name:"에밀 오베센 크벨로",nameEn:"Emil Ovesen Kvello",  pos:"AM (RC), ST (C)",       no:92, age:18, nationality:"노르웨이",   loan:false, seasonStats:{ apps:null, goals:null, assists:null, rating:7.35 } },
    { id:"p_morrison", name:"블레어 모리슨",     nameEn:"Blair Morrison",     pos:"DM, M/AM (C)",          no:null, age:20, nationality:"스코틀랜드",loan:false, seasonStats:{ apps:33,   goals:0,  assists:4,  rating:6.93 } },
    { id:"p_sunomata", name:"토루 스노마타",     nameEn:"Toru Sunomata",      pos:"M/AM (L)",              no:93, age:19, nationality:"일본",       loan:false, seasonStats:{ apps:2,    goals:0,  assists:1,  rating:6.87 } },
    { id:"p_mcwilliam",name:"바니 맥윌리엄",     nameEn:"Barney McWilliam",   pos:"DM, M (C)",             no:33, age:16, nationality:"잉글랜드",   loan:false, seasonStats:{ apps:null, goals:null, assists:null, rating:null } },
    // ── FW ──────────────────────────────────
    { id:"p_thompson", name:"조지 톰프슨",       nameEn:"George Thompson",    pos:"AM (RLC), ST (C)",      no:9,  age:25, nationality:"잉글랜드",   loan:false, seasonStats:{ apps:24,   goals:23, assists:6,  rating:7.47 } },
    { id:"p_tejero",   name:"프란시스코 테헤로", nameEn:"Francisco Tejero",   pos:"M/AM (C)",              no:77, age:20, nationality:"스페인",     loan:false, seasonStats:{ apps:16,   goals:11, assists:7,  rating:7.26 } },
    { id:"p_marfil",   name:"엔리케 마르필",     nameEn:"Enrique Marfil",     pos:"M (L), AM (RL), ST (C)",no:39, age:19, nationality:"스페인",     loan:false, seasonStats:{ apps:1,    goals:1,  assists:0,  rating:6.93 } },
    { id:"p_hughes",   name:"코디 휴즈",         nameEn:"Cody Hughes",        pos:"AM (RL), ST (C)",       no:40, age:22, nationality:"잉글랜드",   loan:false, seasonStats:{ apps:null, goals:null, assists:null, rating:7.12 } },
    { id:"p_baird",    name:"콜린 베어드",       nameEn:"Colin Baird",        pos:"M/AM (C), ST (C)",      no:42, age:17, nationality:"잉글랜드",   loan:false, seasonStats:{ apps:null, goals:null, assists:null, rating:7.80 } },
    { id:"p_bove",     name:"알렉스 보브",       nameEn:"Alex Bove",          pos:"AM (R), ST (C)",        no:95, age:null, nationality:"아일랜드",  loan:false, seasonStats:{ apps:null, goals:null, assists:null, rating:7.82 } },
    { id:"p_lynchey",  name:"애슬리 린치",       nameEn:"Astley Lynchey",     pos:"M/AM (R), ST (C)",      no:31, age:17, nationality:"잉글랜드",   loan:false, seasonStats:{ apps:6,    goals:2,  assists:1,  rating:7.07 } },
    { id:"p_gurrutxaga",name:"고르카 구루차하",  nameEn:"Gorka Gurrutxaga",   pos:"AM (RLC), ST (C)",      no:34, age:20, nationality:"스페인",     loan:false, seasonStats:{ apps:1,    goals:0,  assists:0,  rating:7.20 } },
    { id:"p_santi",    name:"산티",              nameEn:"Santi",              pos:"M/AM (C)",              no:null, age:21, nationality:"잉글랜드",  loan:false, injured:true, seasonStats:{ apps:null, goals:null, assists:null, rating:7.52 } },
    // ── 임대 ────────────────────────────────
    { id:"p_webb",     name:"딜런 웹",           nameEn:"Dylan Webb",         pos:"M/AM (L)",              no:null, age:28, nationality:"잉글랜드",  loan:true,  seasonStats:{ apps:22,   goals:6,  assists:7,  rating:7.14 } },
    { id:"p_havern",   name:"가리 하번",         nameEn:"Gari Havern",        pos:"M/AM (C), ST (C)",      no:null, age:25, nationality:"잉글랜드",  loan:true,  seasonStats:{ apps:11,   goals:4,  assists:1,  rating:6.93 } },
    { id:"p_rafael",   name:"하파엘",            nameEn:"Rafael",             pos:"ST (C)",                no:null, age:25, nationality:"브라질",    loan:true,  seasonStats:{ apps:13,   goals:9,  assists:2,  rating:6.98 } },
    { id:"p_calder",   name:"샘 콜더",           nameEn:"Sam Calder",         pos:"M/AM (C)",              no:null, age:22, nationality:"잉글랜드",  loan:true,  seasonStats:{ apps:24,   goals:4,  assists:5,  rating:7.02 } },
  ],
};
